### ISSUE TITLE
Graphs not generating

### ISSUE THREAD

**Issue by rbgwilson** [mad-ady/smokeping-speedtest#10]
I've configured and verified that the speedtests are being performed correctly but no graphs are generated.

**Comment by mad-ady** [comment]
Are the rrd files not created or are they created but data is not written
to them?

**Comment by rbgwilson** [comment]
It looks like the graphs are but i can't make sense of the graphs.[cid:02362831-934e-4149-aeb1-2bdaa9c4db96]
________________________________

**Comment by mad-ady** [comment]
Can you paste a graph to see how it looks like?
Also, have you applied this patch to store values over 180? https://github.com/oetiker/SmokePing/commit/60419834f224a0735094fd4ad0aac8eac3b15289

**Comment by rbgwilson** [comment]
Yes I've applied the patch to allow value over 180 to be recorded. Here is what the Download and Upload graphs look like.

I reinstalled everything and still don't see the main graphs populated with anything meaningful.
________________________________

**Comment by mad-ady** [comment]
Unfortunately I can't see your graph. But can you use pastebin and paste a rrdtool dump /path/to/rrd.rrd | grep -v NaN?
I am curious what is saved in the RRDs. Also, the module writes some debug information to syslog. You should be able to see it by looking at /var/log/messages or /var/log/syslog. Can you share logs for a polling interval?

**Comment by BitKeeper82** [comment]
Hi mad-ady. I get the same thing, no graphs generated. Pastbin link to rrdtool dump. https://pastebin.com/JJsFPhYp

Output of smokeping --debug below.

speedtest-download: forks 5, timeout for each target 901
speedtest-download: query=/usr/local/bin/speedtest-cli --server 2165 --simple  2>&1
speedtest-download: output: Ping: 23.662 ms
speedtest-download: output: Download: 88.62 Mbit/s
speedtest-download: Got value: 88.62, unit: Mbit/s -> 88620000
speedtest-download: time=8.8620000000e+07 8.8620000000e+07 8.8620000000e+07
speedtest-download: dummy.com: got 8.8620000000e+07 8.8620000000e+07 8.8620000000e+07
speedtest-upload: forks 5, timeout for each target 901
speedtest-upload: query=/usr/local/bin/speedtest-cli --server 2165 --simple  2>&1
speedtest-upload: output: Ping: 23.455 ms
speedtest-upload: output: Download: 62.20 Mbit/s
speedtest-upload: output: Upload: 35.96 Mbit/s
speedtest-upload: Got value: 35.96, unit: Mbit/s -> 35960000
speedtest-upload: time=3.5960000000e+07 3.5960000000e+07 3.5960000000e+07
speedtest-upload: dummy.com: got 3.5960000000e+07 3.5960000000e+07 3.5960000000e+07

**Comment by BitKeeper82** [comment]
That's interesting. It looks like I get a graph when I run smokeping --debug from the command line. Nothing when running as a service.

**Comment by BitKeeper82** [comment]
Ok. It looks like with Ubuntu's smokeping package, the service runs as a user that doesn't have a shell. Change the smoke ping's user to have bash and I get some results, but only on the sub graphs.
![smokeping](https://user-images.githubusercontent.com/24584055/32492712-fb97efdc-c406-11e7-8576-e155f16ba7e7.PNG)
![smokeping01](https://user-images.githubusercontent.com/24584055/32492714-fc265a4c-c406-11e7-99e5-e7e183fe51c5.PNG)

**Comment by mad-ady** [comment]
So polling works correctly. If you look closely the legend in the Overview graphs is updated - you can see 56.3Ms and 29.6Ms. The unit is wrong, since it believes it measures seconds, but the value is correct.
The problem is smokeping was designed for time measurements and it expects low values, that's why the overview scale stops at 1. Apply this workaround, as described in the readme:
```
    For large values the overview graphs will have wrong data. You need to add something like this to your overview section:

+overview
max_rtt = 1000000000

```
