### ISSUE TITLE
Concurrent Probes & Conserving Resources

### ISSUE THREAD

**Issue by h45rd** [mad-ady/smokeping-speedtest#11]
Hi,

Thanks for your work on this useful probe.

Had some issues running it on a low resources box with multiple hosts, due to my ignorance on how smokeping handles probes by default (_concurrentprobes = yes_ and _forks = 5_).
Would you be interested in a change to the readme to clarify what to expect for other noobs like myself?

Basically: by default smokeping runs up to 5 speedtest probes at once, skewing overall results and possibly running into resource trouble on low spec devices.
Setting **forks = 1** will alleviate these issues.

Another thing I noticed: the probe always performs both an upload and download test, no matter the selected measurement.
Adding _extraargs = --no-upload_ or _extraargs = --no-download_ to the respective probe will conserve further resources.

**Comment by mad-ady** [comment]
Hello,

I'd be happy to change the readme, but regarding the no-upload extra
arguments - the problem is I'm using speedtest-cli to perform the
measurements, and last I checked it does all three tests - ping, download,
upload. I can't prevent it from doing the upload.

**Comment by h45rd** [comment]
Hi,

Sorry. Should have been more clear.
With [this commit](https://github.com/sivel/speedtest-cli/commit/3feb38d9d47d41e6b0679e3722dedb4511c437f6) speedtest-cli introduced switches for skipping the upload or download test.
Supplying these switches (_--no-upload_ or _--no-download_) under the **extraargs** parameter works nicely with your probe.
If so inclined, one could probably rewrite the probe to use these switches internally.

**Comment by mad-ady** [comment]
Added your suggestions.
