### ISSUE TITLE
incompatible with speedtest-cli <2.0.2

### ISSUE THREAD

**Issue by ghormoon** [mad-ady/smokeping-speedtest#12]
it took me some time to figure what's wrong, I've been using packaged speedtest-cli, which doesn't support --no-download/--no-upload and it didn't complain until put in debug mode.

this commit is the cause https://github.com/mad-ady/smokeping-speedtest/commit/6391ddd534c324fbacf82be551fb01c98c86d5bd

either make some option to allow old version or put some warning in readme that version >=2.0.2 is required, maybe some error message would be nice too

**Comment by mad-ady** [comment]
Sorry about that. Yes, you're right, it wouldn't work with older versions.
The reason for that commit is that with high-speed tests (1Gbps) you would get two simultaneous tests for upload/download and would get half the speed reported.
