### ISSUE TITLE
How to configure times/day plugin is run?

### ISSUE THREAD

**Issue by Strykar** [mad-ady/smokeping-speedtest#13]
I'd like to run the plugin once every 6 hours instead of the smokeping defaults, how can I do this?

**Comment by mad-ady** [comment]
See the main Readme:

+ speedtest
binary = /usr/local/bin/speedtest-cli
timeout = 300
step = 3600
offset = random
pings = 3

step is in seconds, so you'll need to use 21600 in this case.
