### ISSUE TITLE
Unsure if this is a permission error in Smokeping::probes::speedtest

### ISSUE THREAD

**Issue by Strykar** [mad-ady/smokeping-speedtest#15]
Things were working well until the smokeping master had some recent issues with SSL cert renewal and I noticed the smokeping slave stopped updating.

```
[strykar@slave ~]$ sudo -u smokeping /usr/bin/smokeping --debug --master-url=https://xx.xxxxxx.xx/smokeping.cgi --cache-dir=/var/smokeping/ --shared-secret=/var/smokeping/secret.txt --pid-dir /var/smokeping/
Sent data to Server and got new config in response.
Can't locate IO/Select.pm:   ../IO/Select.pm: Permission denied at /usr/lib/Smokeping/probes/basefork.pm line 21.
BEGIN failed--compilation aborted at /usr/lib/Smokeping/probes/basefork.pm line 21.
Compilation failed in require at /usr/share/perl5/core_perl/base.pm line 137.
	...propagated at /usr/share/perl5/core_perl/base.pm line 159.
BEGIN failed--compilation aborted at /usr/lib/Smokeping/probes/AnotherSSH.pm line 18.
Compilation failed in require at (eval 52) line 1.

[strykar@slave ~]$ getfacl /usr/lib/Smokeping
# file: usr/lib/Smokeping
# owner: smokeping
# group: smokeping
user::rwx
group::r-x
other::r-x

[strykar@slave ~]$ getfacl /usr/lib/perl5/
# file: usr/lib/perl5/
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
```

Running `--debug` on the smokeping master throws:
```
$ sudo -u smokeping /usr/bin/smokeping --debug --config=/etc/smokeping/config
require Smokeping::probes::speedtest failed: Can't locate IO/Select.pm:   ../IO/Select.pm: Permission denied at /usr/lib/Smokeping/probes/basefork.pm line 21, <$fh> line 97.
BEGIN failed--compilation aborted at /usr/lib/Smokeping/probes/basefork.pm line 21, <$fh> line 97.
Compilation failed in require at /usr/share/perl5/core_perl/base.pm line 137, <$fh> line 97.
	...propagated at /usr/share/perl5/core_perl/base.pm line 159, <$fh> line 97.
BEGIN failed--compilation aborted at /usr/lib/Smokeping/probes/speedtest.pm line 18, <$fh> line 97.
Compilation failed in require at (eval 44) line 1, <$fh> line 97.

$ getfacl /usr/lib/Smokeping
# file: usr/lib/Smokeping
# owner: smokeping
# group: smokeping
user::rwx
user:http:rwx
user:smokeping:rwx
group::r-x
mask::rwx
other::r-x

$ getfacl /usr/share/perl5/
# file: usr/share/perl5/
# owner: root
# group: root
user::rwx
user:http:rwx
user:smokeping:rwx
group::r-x
mask::rwx
other::r-x

$ getfacl /usr/lib/perl5/
# file: usr/lib/perl5/
# owner: root
# group: root
user::rwx
user:http:rwx
user:smokeping:rwx
group::r-x
mask::rwx
other::r-x

$ 
```
Is this a permissions issue? The only thing I can think of that has changed is the hostname of the master.

**Comment by mad-ady** [comment]
Hmm, IO::Select is not used directly by Smokeping, but it's needed by the
plugin framework. See if the IO::Select plugin is installed in your perl
installation (both on master and slave), and also see if there is a
IO/Select.pm file in your smokeping installation folder as well (also on
both sides).

**Comment by Strykar** [comment]
I should've mentioned the files and Perl module are present/installed on both machines but aren't present in the Smokeping dir (`/usr/lib/Smokeping`).
I wasn't aware it needed Perl modules in there too.

```
$ sudo find . / -name Select.pm
/usr/lib/perl5/5.30/core_perl/IO/Select.pm
/usr/share/perl5/core_perl/Pod/Select.pm

$ getfacl /usr/lib/perl5/5.30/core_perl/IO/Select.pm
# file: usr/lib/perl5/5.30/core_perl/IO/Select.pm
# owner: root
# group: root
user::r--
group::r--
other::r--

$ sudo cpan IO::Select
Reading '/root/.cpan/Metadata'
Database was generated on Wed, 12 Jun 2019 11:17:03 GMT
IO::Select is up to date (1.40).
```

On the slave:
```
[strykar@slave ~]$ sudo find . / -name Select.pm
/usr/share/perl5/core_perl/Pod/Select.pm
/usr/lib/perl5/5.30/core_perl/IO/Select.pm

[strykar@slave ~]$ getfacl /usr/lib/perl5/5.30/core_perl/IO/Select.pm
# file: usr/lib/perl5/5.30/core_perl/IO/Select.pm
# owner: root
# group: root
user::r--
group::r--
other::r--

[strykar@slave ~]$ sudo cpanm IO::Select
IO::Select is up to date. (1.40)
```

**Comment by mad-ady** [comment]
Under which user is your smokeping running? It's odd that the perl modules
are readable only by root user... They should be world-readable.

**Comment by mad-ady** [comment]
Sorry, I misread the output. They seem to be world readable. Any selinux
active? Are directories that contain the modules readable and executable?

**Comment by Strykar** [comment]
Yea, they are world readable :)
No SElinux, the dir permissions seem fine:
```
$ getfacl /usr/lib/Smokeping
# file: usr/lib/Smokeping
# owner: smokeping
# group: smokeping
user::rwx
user:http:rwx
group::r-x
mask::rwx
other::r-x

[strykar@slave ~]$ getfacl /usr/lib/Smokeping
# file: usr/lib/Smokeping
# owner: smokeping
# group: smokeping
user::rwx
user:http:rwx
user:smokeping:rwx
group::r-x
mask::rwx
other::r-x
```

**Comment by mad-ady** [comment]
Hmm, I don't know. Does the following command output anything?
perl -MIO::Select -e ''

**Comment by Strykar** [comment]
> Hmm, I don't know. Does the following command output anything? perl -MIO::Select -e ''
>
That outputs nothing.

**Comment by mad-ady** [comment]
No output means that the system module is fine.
Not sure what's wrong with your installation. Could be wrong @INC paths?

Here are the permissions for my system:
[root@internetqualitytests smokeping]# find / -name Select.pm
/usr/lib64/perl5/IO/Select.pm
/usr/share/perl5/vendor_perl/Pod/Select.pm
[root@internetqualitytests smokeping]# getfacl /usr/lib64/perl5/IO/Select.pm
getfacl: Removing leading '/' from absolute path names
# file: usr/lib64/perl5/IO/Select.pm
# owner: root
# group: root
user::rw-
group::r--
other::r--

[root@internetqualitytests smokeping]# getfacl
/usr/share/perl5/vendor_perl/Pod/Select.pm
getfacl: Removing leading '/' from absolute path names
# file: usr/share/perl5/vendor_perl/Pod/Select.pm
# owner: root
# group: root
user::rw-
group::r--
other::r--

**Comment by Strykar** [comment]
Unsure what was causing this, I'm closing this as it doesn't appear to be related to smokeping-speedtest in spite of the error.

**Comment by ghost** [comment]
I have the same problem. Usually it disappears if I rebuild smokeping, but it seems weird to rebuild a program "once in a while".
