### ISSUE TITLE
[Feature request] Consider supporting the new official speedtest binary

### ISSUE THREAD

**Issue by Strykar** [mad-ady/smokeping-speedtest#16]
Ookla has published its own binaries ([no source yet](https://www.reddit.com/r/HomeNetworking/comments/dpalqu/speedtestnet_just_launched_an_official_c_cli/f5ttq59?utm_source=share&utm_medium=web2x)):

https://www.speedtest.net/apps/cli
https://www.speedtest.net/insights/blog/introducing-speedtest-cli/

Official announcement thread on Reddit by their engineer - https://www.reddit.com/r/HomeNetworking/comments/dpalqu/speedtestnet_just_launched_an_official_c_cli/

Is this something you'd consider?

**Comment by mad-ady** [comment]
Thanks for the notification. I didn't know about it.
Yes, it is something I'd like to add. Maybe extend the module to support both clients...
No promises when it will be ready, but I hope to do it in a few months at most.

**Comment by Strykar** [comment]
That's great to hear! Take your time, happy to bring it to your attention :smile:

Heads up, they both install to `/usr/bin/speedtest` and @sivel [has refused](https://github.com/sivel/speedtest-cli/issues/663) to rename his binary so it's going to be a case of either one installed, or a custom install of both to different locations.

**Comment by mad-ady** [comment]
That's not a problem. The module has a path to the binary config option, so
you could have both with different probes configured...

**Comment by ghormoon** [comment]
i was looking into if i can somehow help implementin this, but stumbled upon that the official binary can't do only upload or only download test, does everything at once.
is the current solution with the --no-download/--no-upload because it's impossible to collect two graphs from one tool in smokeping or it was just easier to implement so it was not done, but it's possible?

**Comment by mad-ady** [comment]
As far as I know the plugin sends back data to smokeping only for one
measurement. One could do a workaround and save both measurements to some
temp files and on next request read the other measurement from the
tempfile, but it's a bit more messy and one needs to keep track of temp
files, and time has to be consistent to get the last one, etc.
When I get to it I'll consider temp files (but I also accept pull requests
if you want to implement it in the meantime).

**Comment by mad-ady** [comment]
New probe speedtestcli added: https://github.com/mad-ady/smokeping-speedtest/pull/17
