### ISSUE TITLE
Strange data written to influxdb

### ISSUE THREAD

**Issue by jbreitbart** [mad-ady/smokeping-speedtest#19]
I am using your docker container and want to visualize the results using grafana, however it looks like there are no useful values written to my influxdb for the speedtest plugin (others like DNS or FPing are working fine). 

```
> select "min"::field from "speedtest-download" where time >= now() - 120m

name: speedtest-download
time                min
----                ---
1609933916000000000 1e-101
1609933916000000000 1e-101
1609933916000000000 1e-101
1609937490000000000 1e-101
1609937490000000000 1e-101
1609937490000000000 1e-101
> select "max"::field from "speedtest-download" where time >= now() - 120m

> select "median"::field from "speedtest-download" where time >= now() - 120m
name: speedtest-download
time                median
----                ------
1609933916000000000 1e-101
1609933916000000000 1e-101
1609933916000000000 1e-101
1609937490000000000 1e-101
1609937490000000000 1e-101
1609937490000000000 1e-101
```

Any idea what I may be doing wrong?

**Comment by mad-ady** [comment]
Hello!
1e-101 is a placeholder value for a "0" (influxdb tries to convert it to a
string if I just send a plain 0).

Do you get data in your Smokeping graphs for Speedtest? My guess is the
speedtest module may be too old, or may have an issue and can't actually do
the test and thus it's reporting zeros. You'd need to look at the Smokeping
log (should be visible in `docker log my-container`). Look for speedtest
data and results.

Cheers!

**Comment by jbreitbart** [comment]
Thanks a lot for the help. I think I made a mistake while configuring the targets, after I fiddled a bit with the config I seems to work. The speedtest binary still works fine, I started it from a bash inside the container and the results look fine.

What is the unit of the measurements? bytes per second?

**Comment by mad-ady** [comment]
It's bits/s (bps).

**Comment by jbreitbart** [comment]
Thanks again!
