### ISSUE TITLE
speedtest.pm does not populate rrd

### ISSUE THREAD

**Issue by jhenkins** [mad-ady/smokeping-speedtest#2]
Hello,

This looks like an excellent tool, and I have seen other people whom have managed to get it to graph successfully. However, I cannot get it to work, so I would really appreciate any assistance. I have followed the instructions in the README.md file, and created the local0 logging for debug purposes. When Smokeping runs the probe, it definitely gets data back from speedtest-cli (here is a snippet from the log):

---start---
Oct 18 21:13:45 jandev smokeping[37079]: query=/usr/local/bin/speedtest-cli --server 3699 --simple 2>&1
Oct 18 21:14:21 jandev smokeping[37079]: output: Ping: 52.692 ms
Oct 18 21:14:21 jandev smokeping[37079]: output: Download: 7.47 Mbit/s
Oct 18 21:14:21 jandev smokeping[37079]: output: Upload: 2.95 Mbit/s
Oct 18 21:14:21 jandev smokeping[37079]: Got value: 2.95, unit: Mbit/s -> 2950000
Oct 18 21:14:21 jandev smokeping[37079]: time=2.9500000000e+06 2.9500000000e+06 2.9500000000e+06
---end---

My Probes section looks like this:

---start---
- speedtest
  binary = /usr/local/bin/speedtest-cli
  timeout = 300
  step = 3600
  offset = random
  pings = 3

++ speedtest-download
measurement = download

++ speedtest-upload
measurement = upload
---end---

My Targets entry looks like this:

---start---
- SPEEDTEST
  menu = Speedtest
  title = Speedtest Results

++ download_from_Virgin_Croydon
menu = download_from_Virgin_Croydon
title = download_from_Virgin_Croydon
probe = speedtest-download
server = 3699
measurement = download
host = dummy.com

++ upload_to_Virgin_Croydon
menu = upload_to_Virgin_Croydon
title = upload_to_Virgin_Croydon
probe = speedtest-upload
server = 3699
measurement = upload
host = dummy.com
---end---

My Overview area in the Presentation file:

---start---
- overview

width = 600
height = 50
range = 10h
max_rtt = 1000000000
---end---

And yet, no data in the generated graphs. Is there anything wrong with the above? If not, what else can I do in order to get this to work?

Thanks in advance!

Regards,
Jan Henkins

**Comment by jhenkins** [comment]
Hello,

I should have read the updated line at the bottom of the README, which of course I did not! :-P
Applying that patch helped, I now have graphs! 

Case closed! 

Regards,
Jan Henkins

**Comment by mad-ady** [comment]
Yeah, I had forgotten about that change when I first created the readme.
The next smokeping release will include that change.
