### ISSUE TITLE
speedtest --version' does not return a meaningful version number

### ISSUE THREAD

**Issue by benscha** [mad-ady/smokeping-speedtest#20]
i have the folllowing issue:

after installing i tried to start smokeping service with no success... may someone help me?

OS:
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"

`smokeping --version
2.007003
`

`Jan 15 18:14:05 tousure-rpi systemd[1]: Starting Latency Logging and Graphing System...
Jan 15 18:14:08 tousure-rpi smokeping[10962]: ### parsing /usr/local/bin/speedtest-cli output... OK (version 5)
Jan 15 18:14:08 tousure-rpi smokeping[10962]: ### parsing /usr/local/bin/speedtest-cli output... OK (version 5)
Jan 15 18:14:09 tousure-rpi smokeping[10962]: ERROR: output of '/usr/local/bin/speedtest --version' does not return a meaningful version number. Is speedtest installed?
Jan 15 18:14:09 tousure-rpi smokeping[10962]:  at (eval 64) line 1.
`

```
speedtest --version
speedtest-cli 2.1.2
Python 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
```

thx

**Comment by Strykar** [comment]
Post the output of `/usr/local/bin/speedtest --version`
I suspect it may be another version of speedtest on the OS.

**Comment by benscha** [comment]
/usr/local/bin/speedtest --version
speedtest-cli 2.1.2
Python 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]

**Comment by mad-ady** [comment]
Please show your probe configuration.
Note that two different speedtest binaries are supported:
- Ookla binary needs to be configured as "speedtestcli"
- Sievel binary needs to be configured as "speedtest"

Otherwise it won't work and may complain about not understanding the binary
version.

**Comment by ma3s7ro** [comment]
Hi I have the same issue. 
 /usr/bin/speedtest --version
2.0.2
/usr/local/bin/speedtest --version
2.0.2
/usr/local/bin/speedtest-cli --version
2.0.2
/usr/bin/speedtest-cli --version
2.0.2

My Probes output
+ speedtestcli
binary = /usr/bin/speedtest
timeout = 300
forks = 1
step = 3600
offset = random
pings = 3

+ speedtest
binary = /usr/local/bin/speedtest-cli
timeout = 300
forks = 1
step = 3600
offset = random
pings = 3


What I should change in Probes for fix this error. 
Thanks a lot.

**Comment by mad-ady** [comment]
Looks like you have sievel's version saved multiple times. Ookla's output
is something like:
```
/usr/bin/speedtest --version
Speedtest by Ookla 1.0.0.2 (5ae238b) Linux/x86_64-linux-musl
5.4.0-77-generic x86_64

The official command line client for testing the speed and performance
of your internet connection.
```
So you just need to configure "speedtest" in your probes section.

**Comment by ma3s7ro** [comment]
Thanks a lot. 
Fixed!
