### ISSUE TITLE
speedtestcli (Ookla binary) produces heavy traffic

### ISSUE THREAD

**Issue by r2ixuz** [mad-ady/smokeping-speedtest#23]
Due to the fact that the official Ookla binary can only do an upload speedtest combined with a download speedtest, this produces way more traffic than I expected.

On my 1000Mbit/s download and 50 Mbit/s upload cable connection (DOCSIS) this generates the following traffic if you select tests every hour (3600s):

1 GB download traffic for the download probe and 1 GB download traffic for the upload probe (even it is not needed...). Makes 2 GB download traffic per hour, 48 GB per day and 1488 GB per month with 31 days. Wow, normally I got 1,5 TB per month without this smokeping speedtest.

And using the other opensource speedtest variant is no option, due to its poor design. It generates nearly everytime wrong (too low) numbers for up- and download.

**Comment by mad-ady** [comment]
Yes, this is a known limitation of the ookla binary.

The thing is - the plugin could work around the problem and create a cache
file to store both results and serve the cached result, but it adds more
complexity and may introduce problems (e.g. when the download test is
scheduled once per hour and the upload test is once every 10 minutes).

I would accept a PR for a temporary cache implementation that is
user-selectable.
