### ISSUE TITLE
[Feature request] Add Latency graph

### ISSUE THREAD

**Issue by svenvg93** [mad-ady/smokeping-speedtest#24]
As the title suggest would it be possible to add a graph that shows the latency (ping) to Speedtest Server. If possible the same for Jitter and packet loss?

**Comment by mad-ady** [comment]
Well, it is possible!

In the smokeping config you can add a ping probe, like this:
```

+ speedtest
binary = /usr/local/bin/speedtest-cli
timeout = 300
forks = 1
step = 3600
offset = random
pings = 3

++ speedtest-download
measurement = download

++ speedtest-upload
measurement = upload

++ speedtest-ping
measurement = ping

```
Inside the targets, you can add something like:
```
++++ upload_to_MY_ISP_on_IQ-01-lan
menu = upload_to_MY_ISP_on_IQ-01-lan
title = upload_to_MY_ISP_on_IQ-01-lan
probe = speedtest-ping
server = 1234
measurement = ping
host = dummy.com
slaves = IQ-01-lan
```

I've added influxdb support to smokeping and measurements from all probes can be logged into an influxdb database - see this enhancement: https://github.com/oetiker/SmokePing/issues/201

Inside influxdb you have access to the raw measurements for upload/download/ping or whatever probes you have:
```
> show measurements;

name: measurements
name
----
CurlFullPage
FPing
YoutubeDL
speedtest-download
speedtest-upload
speedtest-ping
speedtestcli-download
speedtestcli-upload

```
You can use grafana to generate graphs for loss/min/max (which I interpret as jitter). Check out this dashboard as an example: https://grafana.com/grafana/dashboards/12459

Feel free to reopen this if you have other questions.
