### ISSUE TITLE
No graphs

### ISSUE THREAD

**Issue by xelfer** [mad-ady/smokeping-speedtest#3]
Similar to https://github.com/mad-ady/smokeping-speedtest/issues/2 but I have patched the file as suggested in the README and i'm not getting any graphs.. any ideas where I may be going wrong?

Screenshot: https://i.imgur.com/tZscshh.png

Logs seem good:

> Aug 24 06:47:21 pi smokeping[29581]: query=/usr/local/bin/speedtest-cli  --simple 2>&1
> Aug 24 06:47:43 pi smokeping[29423]: output: Ping: 125.462 ms
> Aug 24 06:47:43 pi smokeping[29423]: output: Download: 3.25 Mbit/s
> Aug 24 06:47:43 pi smokeping[29423]: Got value: 3.25, unit: Mbit/s -> 3250000
> Aug 24 06:47:43 pi smokeping[29423]: time=3.2500000000e+06 3.2500000000e+06 3.2500000000e+06

Probes:

>   + speedtest
>   binary = /usr/local/bin/speedtest-cli
>   timeout = 300
>   step = 120
>   offset = random
>   pings = 3
> 
> ++ speedtest-download
> measurement = download
> 
> ++ speedtest-upload
> measurement = upload

Targets:

> ++ Google
> menu = Google
> title = Google - 8.8.8.8
> host = 8.8.8.8
> 
> ++ speedtest-download
> menu = speedtest download
> title = speedtest download
> probe = speedtest-download
> measurement = download
> host = dummy.com
> 
> ++ speedtest-upload
> menu = speedtest upload
> title = speedtest upload
> probe = speedtest-upload
> measurement = upload
> host = dummy.com

Also tested with a server config (though I wanted it to detect closest):

> Aug 24 07:00:49 pi smokeping[31484]: query=/usr/local/bin/speedtest-cli --server 5666 --simple 2>&1
> Aug 24 07:00:50 pi smokeping[31188]: output: Ping: 62.294 ms
> Aug 24 07:00:50 pi smokeping[31188]: output: Download: 3.24 Mbit/s
> Aug 24 07:00:50 pi smokeping[31188]: output: Upload: 0.58 Mbit/s
> Aug 24 07:00:50 pi smokeping[31188]: Got value: 0.58, unit: Mbit/s -> 580000
> Aug 24 07:00:50 pi smokeping[31188]: time=5.8000000000e+05 5.8000000000e+05 5.8000000000e+05

The google target seems to work fine. Any help appreciated!

edit:
Also dumped the rrd file here: https://gist.github.com/4c110853d41bb6eca2c8ffd82b11ba14

Smokeping.pm line 560 + 561:

> ```
>                           "DS:median:GAUGE:".(2*$step).":0:U",
>                          (map { "DS:ping${_}:GAUGE:".(2*$step).":0:U" }
> ```

**Comment by xelfer** [comment]
Well this is the worst kind of update. I changed nothing and it's suddenly working. :(

I guess some combination of something above and restarting the service made it work.. but I'm really confused as to why it wasn't working before.

**Comment by mad-ady** [comment]
Yeah, your output looked ok. You have to wait for about 2\* polling time to get values on your graphs, but otherwise the rrd looked fine. Glad it worked :)

**Comment by EmilNachev** [comment]
I have no graph :(

**Comment by mad-ady** [comment]
You need to wait for at least two polling cycles to get graphs. Otherwise
run smokeping in debug mode and see what happens.
