### ISSUE TITLE
Feature request: Digital Ocean speedtest

### ISSUE THREAD

**Issue by Strykar** [mad-ady/smokeping-speedtest#4]
Any chance support for http://speedtest-nyc1.digitalocean.com could be built in?

**Comment by mad-ady** [comment]
Well, if you find a backend script that can do the tests or if it is supported already by the speedtest-cli scripts, then sure. Otherwise, you'd need to reverse-engineer what their flash plugin does and write your own backend...

**Comment by Strykar** [comment]
Fair enough, thanks.
