### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by xelfer** [mad-ady/smokeping-speedtest#5]
This plugin stopped working for me yesterday (having changed nothing in my setup) - is anyone else experiencing this? I'm wondering if speedtest blocked it.

**Comment by mad-ady** [comment]
You need to see if you need to update speedtest-cli, or if you can do
speedtest tests from the same IP (in case you got blacklisted). I'm not
using it anymore, so I can't confirm nor deny.

**Comment by xelfer** [comment]
Apologies, I thought this was the speedtest-cli repo! my bad. 

Will report it to them :)
