### ISSUE TITLE
extra arguments?

### ISSUE THREAD

**Issue by xelfer** [mad-ady/smokeping-speedtest#6]
sorry to bother you again :)

is there a way to add extra command line arguments to the binary command? I see the curl probe for smokeping has an 'extraargs' section but I'm not sure how I'd go about adding it to the speedtest one.

(i want to add "--secure" as a work around to the current speedtest-cli issues)

**Comment by mad-ady** [comment]
I've just made a commit to add this support. Kindly try it out. You will need to add a extraargs parameter with the value you want to pass to speedtest-cli in your probe config (similar to server).

**Comment by xelfer** [comment]
works perfectly, thank you so much for the quick reply and solution!
