### ISSUE TITLE
Add support for median upload/download speeds in graph details

### ISSUE THREAD

**Issue by Strykar** [mad-ady/smokeping-speedtest#7]
Currently, the detailed graph plots the upload/download speeds and in the details below the plot, it displays median RTT and packet loss, which is great.

For unstable connections, median up/down speeds viewed over the last 3-6 months is often more useful, like when tweaking QoS to be relevant to current (most likely) available bandwidth.

Could we show all 3 median RTT, packet loss and up/down values or have a choice what to display in the details?

**Comment by mad-ady** [comment]
What do you mean by "details"? The graph legend, or the overview graph?

**Comment by mad-ady** [comment]
I think you mean the legend. As far as I know those values are directly
controlled by Smokeping, and not the plugin, so you'll need to ask
Smokeping's author for help, or edit the source yourself (I removed some of
the details for clarity)

**Comment by Strykar** [comment]
Yes, see http://imgur.com/a/84dKX

**Comment by Strykar** [comment]
Isn't the median RTT is being reported by smokeping/speedtest?

**Comment by mad-ady** [comment]
Can you post a picture of the graph? I haven't used the plugin in 1 year...

**Comment by Strykar** [comment]
I have, see comment 4

**Comment by mad-ady** [comment]
Sorry, I forgot to update this.
I've checked - the graph legend is completely handled within Smokeping.
Look into https://github.com/oetiker/SmokePing/blob/master/lib/Smokeping.pm
around line 1292.

**Comment by Strykar** [comment]
Alright, thanks.
